version: 2
jobs:
  jdk-8:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
      - image: circleci/postgres:9.6.3-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
    steps:
      - checkout
      - run: echo "Hello CircleCI!"
      - run: 
          name: wait for db
          command: dockerize -wait tcp://127.0.0.1:5432 -timeout 120s
